INSERT INTO `tb_direcciones` (`municipio`, `comunidad`) 
VALUES 
	('San Salvador', 'Bocaja'),
	('San Salvador', 'Bominthza'),
	('San Salvador', 'Boxaxni'),
	('San Salvador', 'Boxtha Chico'),		
	('San Salvador', 'Bóxtha Chico'),
	('San Salvador', 'Casa Blanca'),
	('San Salvador', 'Casa Grande'),
	('San Salvador', 'Caxuxi'),
	('San Salvador', 'Cañada Grande'),
	('San Salvador', 'Cerro Blanco'),
	('San Salvador', 'Chichimecas'),
	('San Salvador', 'Demacu'),
	('San Salvador', 'Dengandhó de Juárez'),
	('San Salvador', 'Dextho de Victoria'),
	('San Salvador', 'Déxtho de Victoria'),
	('San Salvador', 'Ejido Santa Teresa (El Tablón)'),
	('San Salvador', 'El Bondho'),
	('San Salvador', 'El Cerrito'),
	('San Salvador', 'El Colorado'),
	('San Salvador', 'El Durazno (El Durazno de Flores Magón)'),
	('San Salvador', 'El Fresno'),
	('San Salvador', 'El Gómez'),
	('San Salvador', 'El Mezquital'),
	('San Salvador', 'El Mothé'),
	('San Salvador', 'El Olvera'),
	('San Salvador', 'El Puerto Lázaro Cárdenas'),
	('San Salvador', 'El Rodrigo'),
	('San Salvador', 'El Tablón'),
	('San Salvador', 'Francisco Villa'),
	('San Salvador', 'Herminia Olguín Díaz'),
	('San Salvador', 'La Flor'),
	('San Salvador', 'La Hacienda'),
	('San Salvador', 'La Palma'),
	('San Salvador', 'Lagunilla'),
	('San Salvador', 'Leandro Valle'),
	('San Salvador', 'Media Luna [Fraccionamiento]'),
	('San Salvador', 'Pacheco de Allende'),
	('San Salvador', 'Pacheco Leandro Valle'),
	('San Salvador', 'Poxindeje de Morelos'),
	('San Salvador', 'Quemtha'),
	('San Salvador', 'El Rincón'),
	('San Salvador', 'San Antonio Abad'),
	('San Salvador', 'San Antonio Zaragoza'),
	('San Salvador', 'San José Doxey'),
	('San Salvador', 'San Miguel Acambay'),
	('San Salvador', 'San Salvador'),
	('San Salvador', 'Santa María Amajac'),
	('San Salvador', 'Teofani'),
	('San Salvador', 'Tothie'),
	('San Salvador', 'Tothie (Tothie de Rojo Gómez)'),
	('San Salvador', 'Vixtha de Madero'),
	('San Salvador', 'Xuchitlán'),

	('Actopan', '2 Cerritos'),
	('Actopan', 'Actopan'),
	('Actopan', 'Actopan Centro'),
	('Actopan', 'Benito Juárez'),
	('Actopan', 'Bothi Baji'),
	('Actopan', 'Bothibaji'),
	('Actopan', 'Boxaxni'),
	('Actopan', 'Canguihuindo'),
	('Actopan', 'Casa Blanca'),
	('Actopan', 'Cañada Chica Antigua'),
	('Actopan', 'Cañada Chica Campo Aéreo'),
	('Actopan', 'Chicavasco'),
	('Actopan', 'Cuarta Manzana Chicavasco (La Ladera Chicavasco)'),
	('Actopan', 'Cuauhtémoc'),
	('Actopan', 'Cuauhtémoc [Colonia]'),
	('Actopan', 'Dajiedhi'),
	('Actopan', 'Daxtha'),
	('Actopan', 'El Apartadero'),
	('Actopan', 'El Boxtha'),
	('Actopan', 'El Daxtha'),
	('Actopan', 'El Huaxtho'),
	('Actopan', 'El Huaxtito'),
	('Actopan', 'El Palomo'),
	('Actopan', 'El Paraje'),
	('Actopan', 'El Porvenir'),
	('Actopan', 'El Senthé'),
	('Actopan', 'Francisco Constancio Azpeitia García'),
	('Actopan', 'Fundición A'),
	('Actopan', 'Fundición B'),
	('Actopan', 'Genaro Guzmán Mayer'),
	('Actopan', 'Huaxto de Emiliano Zapata'),
	('Actopan', 'La Ardilla (Tierras Coloradas)'),
	('Actopan', 'La Escoba'),
	('Actopan', 'La Estancia'),
	('Actopan', 'La Loma'),
	('Actopan', 'La Palma'),
	('Actopan', 'La Peña'),
	('Actopan', 'La Presa'),
	('Actopan', 'La Quinta'),
	('Actopan', 'La Segunda Manzana de Magdalena (El Arco)'),
	('Actopan', 'Las Mecas'),
	('Actopan', 'Los Olivos'),
	('Actopan', 'Magdalena'),
	('Actopan', 'Manzana de Golondrinas'),
	('Actopan', 'Mesa Chica'),
	('Actopan', 'Nuevo Actopan'),
	('Actopan', 'Pabellón Gastronómico'),
	('Actopan', 'Plomosas'),
	('Actopan', 'Pozo Grande'),
	('Actopan', 'Rancho Osorios'),
	('Actopan', 'San Andrés'),
	('Actopan', 'San Andrés Tianguistengo'),
	('Actopan', 'San Diego Canguihuindo'),
	('Actopan', 'San Isidro'),
	('Actopan', 'San Pedrito'),
	('Actopan', 'Santa María Magdalena'),
	('Actopan', 'Saucillo'),
	('Actopan', 'Segunda Manzana Chicavasco (El Pozo)'),
	('Actopan', 'Xideje'),

	('El Arenal', '20 de Noviembre'),
	('El Arenal', '20 de Noviembre [Colonia]'),
	('El Arenal', 'Alfonso Gutiérrez'),
	('El Arenal', 'Antonio Rosales'),
	('El Arenal', 'Antonio Vizcaíno'),
	('El Arenal', 'Casa Blanca (El Camichín)'),
	('El Arenal', 'Cerro de la Cantera'),
	('El Arenal', 'Chimalpa'),
	('El Arenal', 'Chimilpa'),
	('El Arenal', 'Colonia Cuisillos (Huaxtla de Orendain)'),
	('El Arenal', 'Cosahuayán Grande'),
	('El Arenal', 'Crucero de Huaxtla'),
	('El Arenal', 'De Tejas'),
	('El Arenal', 'Don Gil [Granja]'),
	('El Arenal', 'El Arenal'),
	('El Arenal', 'El Arenal [Granja Avícola]'),
	('El Arenal', 'El Bocja'),
	('El Arenal', 'El Guayabo Dos'),
	('El Arenal', 'El Guayabo Uno'),
	('El Arenal', 'El Jiadi'),
	('El Arenal', 'El Llano'),
	('El Arenal', 'El Meje'),
	('El Arenal', 'El Novillero (El Polvorín)'),
	('El Arenal', 'El Ojua'),
	('El Arenal', 'El Paje'),
	('El Arenal', 'El Palo Verde'),
	('El Arenal', 'El Panchote'),
	('El Arenal', 'El Pinar [Granja]'),
	('El Arenal', 'El Polvorín'),
	('El Arenal', 'El Puerto de San Pedro'),
	('El Arenal', 'El Rincón'),
	('El Arenal', 'El Rincón'),
	('El Arenal', 'El Roble'),
	('El Arenal', 'El Sabino'),
	('El Arenal', 'Emiliano Zapata'),
	('El Arenal', 'Empalme de Orendain (Potrero la Presa)'),
	('El Arenal', 'Fray Francisco'),
	('El Arenal', 'Guadalupe Ibarra'),
	('El Arenal', 'Haciendas de Huaxtla'),
	('El Arenal', 'Huaxtla'),
	('El Arenal', 'Huerta las Hiedras'),
	('El Arenal', 'Huertas el Zamorano [Asociación de Propietarios y Colonos]'),
	('El Arenal', 'La Atarjea'),
	('El Arenal', 'La Azteca'),
	('El Arenal', 'La Cantera'),
	('El Arenal', 'La Cima [Fraccionamiento]'),
	('El Arenal', 'La Garita (La Mina)'),
	('El Arenal', 'La Laguna Colorada'),
	('El Arenal', 'La Loma'),
	('El Arenal', 'La Loma'),
	('El Arenal', 'La Manzana Uno'),
	('El Arenal', 'La Mesa'),
	('El Arenal', 'La Minita'),
	('El Arenal', 'La Misión (Los Pitufos)'),
	('El Arenal', 'La Sala (La Caliente)'),
	('El Arenal', 'La Soledad'),
	('El Arenal', 'La Tapatía [Granja]'),
	('El Arenal', 'Laguna Seca'),
	('El Arenal', 'Las Palmas'),
	('El Arenal', 'Las Peñitas'),
	('El Arenal', 'Las Porquerizas [Granja la Presa]'),
	('El Arenal', 'Las Tortugas'),
	('El Arenal', 'Las Tortugas [Fraccionamiento]'),
	('El Arenal', 'Los Cuates'),
	('El Arenal', 'Los Guayabos'),
	('El Arenal', 'Los Robles'),
	('El Arenal', 'Margarita Maza de Juárez'),
	('El Arenal', 'Ninguno'),
	('El Arenal', 'Ojo de Agua San José Tepenene'),
	('El Arenal', 'Ojo de Agua Santa Rosa'),
	('El Arenal', 'Padre Castro'),
	('El Arenal', 'Peñitas [Granja]'),
	('El Arenal', 'Pomona [Granja]'),
	('El Arenal', 'Primavera [Granja]'),
	('El Arenal', 'Puente de las Tortugas'),
	('El Arenal', 'Puerto del Oro'),
	('El Arenal', 'Rancho Alejandro Torres'),
	('El Arenal', 'Rancho de Trino'),
	('El Arenal', 'Rancho el Durazno'),
	('El Arenal', 'Rancho el Trébol'),
	('El Arenal', 'Rancho el Venado'),
	('El Arenal', 'Rancho la Esmeralda'),
	('El Arenal', 'Rancho la Loma'),
	('El Arenal', 'Rancho las Juntas'),
	('El Arenal', 'Rancho las Pilas'),
	('El Arenal', 'Rancho los Paraísos'),
	('El Arenal', 'Rancho San Francisco'),
	('El Arenal', 'Río Habitad (El Río Contry Club)'),
	('El Arenal', 'San Jerónimo'),
	('El Arenal', 'San José Tepenene'),
	('El Arenal', 'Santa Cruz Del Astillero'),
	('El Arenal', 'Santa Quiteria'),
	('El Arenal', 'Santa Quitería'),
	('El Arenal', 'Santa Rosa'),
	('El Arenal', 'Santa Sofía'),
	('El Arenal', 'Tepenene'),
	('El Arenal', 'Tres Mujeres'),
	('El Arenal', 'Uña de Gato'),
	('El Arenal', 'Villas de Huaxtla'),
	('El Arenal', 'Villas del Arenal'),
	('El Arenal', 'Villas del Arenal'),

	('Francisco I. Madero', 'Arambó'),
	('Francisco I. Madero', 'Barrio el Bravo'),
	('Francisco I. Madero', 'Barrio el Quince'),
	('Francisco I. Madero', 'Barrio los Amigos'),
	('Francisco I. Madero', 'Barrio Nuevo México'),
	('Francisco I. Madero', 'Barrio San Antonio'),
	('Francisco I. Madero', 'Bocamiño'),
	('Francisco I. Madero', 'Compuerta el Trece'),
	('Francisco I. Madero', 'Cuarta Demarcación (Barrio los Violines) [Colonia]'),
	('Francisco I. Madero', 'Dengantzha'),
	('Francisco I. Madero', 'Doctor José G. Parres'),
	('Francisco I. Madero', 'El Horno [Colonia]'),
	('Francisco I. Madero', 'El Hoyo'),
	('Francisco I. Madero', 'El Mendoza'),
	('Francisco I. Madero', 'El Mexe'),
	('Francisco I. Madero', 'El Porvenir'),
	('Francisco I. Madero', 'El Potrero'),
	('Francisco I. Madero', 'El Rancho'),
	('Francisco I. Madero', 'El Represo'),
	('Francisco I. Madero', 'El Rosario'),
	('Francisco I. Madero', 'El Rosario [Colonia]'),
	('Francisco I. Madero', 'El Rosario Tepatepec'),
	('Francisco I. Madero', 'El Tapia'),
	('Francisco I. Madero', 'El Veinte [Colonia]'),
	('Francisco I. Madero', 'El Villano'),
	('Francisco I. Madero', 'Emiliano Zapata (Los Morales) [Colonia]'),
	('Francisco I. Madero', 'Francisco Villa [Colonia]'),
	('Francisco I. Madero', 'Jagüey del Gonzudi'),
	('Francisco I. Madero', 'La Comunidad'),
	('Francisco I. Madero', 'La Cruz'),
	('Francisco I. Madero', 'La Mora'),
	('Francisco I. Madero', 'La Puerta'),
	('Francisco I. Madero', 'Las Coronas'),
	('Francisco I. Madero', 'Las Fuentes'),
	('Francisco I. Madero', 'Los Filtros'),
	('Francisco I. Madero', 'Lázaro Cárdenas'),
	('Francisco I. Madero', 'Lázaro Cárdenas (El Mexe) [Colonia]'),
	('Francisco I. Madero', 'San José Boxay'),
	('Francisco I. Madero', 'San Juan Tepa'),
	('Francisco I. Madero', 'Tepatepec'),
	('Francisco I. Madero', 'Tepeyac [Granja]'),

	('Acatlán', 'Acatlán'),
	('Acaxochitlán', 'Acaxochitlán'),
	('Agua Blanca de Iturbide', 'Agua Blanca de Iturbide'),
	('Ajacuba', 'Ajacuba'),
	('Alfajayucan', 'Alfajayucan'),
	('Almoloya', 'Almoloya'),
	('Apan', 'Apan'),
	('Atitalaquia', 'Atitalaquia'),
	('Atlapexco', 'Atlapexco'),
	('Atotonilco de Tula', 'Atotonilco de Tula'),
	('Atotonilco el Grande', 'Atotonilco el Grande'),
	('Calnali', 'Calnali'),
	('Cardonal', 'Cardonal'),
	('Chapantongo', 'Chapantongo'),
	('Chapulhuacán', 'Chapulhuacán'),
	('Chilcuautla', 'Chilcuautla'),
	('Cuautepec de Hinojosa', 'Cuautepec de Hinojosa'),
	('Eloxochitlán', 'Eloxochitlán'),
	('Emiliano Zapata', 'Emiliano Zapata'),
	('Epazoyucan', 'Epazoyucan'),
	('Huasca de Ocampo', 'Huasca de Ocampo'),
	('Huautla', 'Huautla'),
	('Huazalingo', 'Huazalingo'),
	('Huehuetla', 'Huehuetla'),
	('Huejutla de Reyes', 'Huejutla de Reyes'),
	('Huichapan', 'Huichapan'),
	('Ixmiquilpan', 'Ixmiquilpan'),
	('Jacala de Ledezma', 'Jacala de Ledezma'),
	('Jaltocán', 'Jaltocán'),
	('Juárez Hidalgo', 'Juárez Hidalgo'),
	('La Misión', 'La Misión'),
	('Lolotla', 'Lolotla'),
	('Metepec', 'Metepec'),
	('Metztitlán', 'Metztitlán'),
	('Mineral de la Reforma', 'Mineral de la Reforma'),
	('Mineral del Chico', 'Mineral del Chico'),
	('Mineral del Monte', 'Mineral del Monte'),
	('Mixquiahuala de Juárez', 'Mixquiahuala de Juárez'),
	('Molango de Escamilla', 'Molango de Escamilla'),
	('Nicolás Flores', 'Nicolás Flores'),
	('Nopala de Villagrán', 'Nopala de Villagrán'),
	('Omitlán de Juárez', 'Omitlán de Juárez'),
	('Pachuca de Soto', 'Pachuca de Soto'),
	('Pacula', 'Pacula'),
	('Pisaflores', 'Pisaflores'),
	('Progreso de Obregón', 'Progreso de Obregón'),
	('San Agustín Metzquititlán', 'San Agustín Metzquititlán'),
	('San Agustín Tlaxiaca', 'San Agustín Tlaxiaca'),
	('San Bartolo Tutotepec', 'San Bartolo Tutotepec'),
	('San Felipe Orizatlán', 'San Felipe Orizatlán'),
	('Santiago de Anaya', 'Santiago de Anaya'),
	('Santiago Tulantepec de Lugo Guerrero', 'Santiago Tulantepec de Lugo Guerrero'),
	('Singuilucan', 'Singuilucan'),
	('Tasquillo', 'Tasquillo'),
	('Tecozautla', 'Tecozautla'),
	('Tenango de Doria', 'Tenango de Doria'),
	('Tepeapulco', 'Tepeapulco'),
	('Tepehuacán de Guerrero', 'Tepehuacán de Guerrero'),
	('Tepeji del Río de Ocampo', 'Tepeji del Río de Ocampo'),
	('Tepetitlán', 'Tepetitlán'),
	('Tetepango', 'Tetepango'),
	('Tezontepec de Aldama', 'Tezontepec de Aldama'),
	('Tianguistengo', 'Tianguistengo'),
	('Tizayuca', 'Tizayuca'),
	('Tlahuelilpan', 'Tlahuelilpan'),
	('Tlahuiltepa', 'Tlahuiltepa'),
	('Tlanalapa', 'Tlanalapa'),
	('Tlanchinol', 'Tlanchinol'),
	('Tlaxcoapan', 'Tlaxcoapan'),
	('Tolcayuca', 'Tolcayuca'),
	('Tula de Allende', 'Tula de Allende'),
	('Tulancingo de Bravo', 'Tulancingo de Bravo'),
	('Villa de Tezontepec', 'Villa de Tezontepec'),
	('Xochiatipan', 'Xochiatipan'),
	('Xochicoatlán', 'Xochicoatlán'),
	('Yahualica', 'Yahualica'),
	('Zacualtipán de Ángeles', 'Zacualtipán de Ángeles'),
	('Zapotlán de Juárez', 'Zapotlán de Juárez'),
	('Zempoala', 'Zempoala'),
	('Zimapán', 'Zimapán');